Terraform code for deployment
GoogleCloudPlatform/bigquery-antipattern-recognition pull request #10
Opened 2023-06-08 12:54 UTC by vikaskumawat80

Added terraform for automated deployment. Code will perform:

- Creation of Artifact Registry
- Creation of Cloud Run Job
- Creation of Cloud Scheduler
- Creation of Service Accounts with IAM roles
- Build and push Image to Artifact Registry

2023-06-12 03:34 UTC, ppaglilla requested changes
Left a couple of comments!

The interesting bit I think we should add is having terraform create the output table, which is required to be in place before runs right now.

Let's also add a mention to this in the top-level README!

2023-06-12 03:34 UTC, ppaglilla commented on terraform/main.tf
Can we add the creation of the output table to the Terraform module? We can have a variable to enable/disable the creation of the table, similar to the one we have for Cloud Scheduler.

Creating that table is a requirement right now, so having it done by Terraform itself would make sense.

2023-06-12 03:34 UTC, ppaglilla commented on terraform/README.md
Can we explain a little what the module deploys in the README? Sort of as an introduction to this way to deploy the tool.

Something along the lines of _This module builds and deploys the BigQuery Antipattern Recognition tool to Cloud Run Jobs. The tool will be configured to, in each execution, perform antipattern recognition of all jobs run during the previous 24 hours and write the results to a BigQuery table. It can optionally deploy a Cloud Scheduler cron to run the job on a schedule._

Bonus points if we add this to the top-level readme as well 😄

2023-06-12 04:27 UTC, ppaglilla commented on terraform/main.tf
> +resource "google_project_service" "project_service" {
Small follow up question. I did a test deployment and, as expected, these APIs were disabled when running `terraform destroy` to tear everything down.

The thing is they get disabled even if they were already enabled and there are other resources in them. For example, I had a few Artifact Registry repositories for other uses and the API got disabled anyway.

Coming from a far from Terraform expert, is there anyway we can avoid that?

2023-06-14 10:23 UTC, vikaskumawat80 commented
Updated the code to fix API issue, readme and BQ Table

2023-06-19 14:59 UTC, ppaglilla requested changes

2023-06-19 14:59 UTC, ppaglilla commented on terraform/main.tf
> +  deletion_protection = false
We're missing the schema for the table here. Suggesting what we need.

This is the only extra change we need. Let's add it and we can merge!

```suggestion
  deletion_protection = false
  
  schema = <<EOF
[
    {
        "name": "job_id",
        "type": "STRING",
        "mode": "NULLABLE"
    },
    {
        "name": "query",
        "type": "STRING",
        "mode": "NULLABLE"
    },
    {
        "name": "recommendation",
        "type": "RECORD",
        "mode": "REPEATED",
        "fields": [
            {
                "name": "name",
                "type": "STRING",
                "mode": "NULLABLE"
            },
            {
                "name": "description",
                "type": "STRING",
                "mode": "NULLABLE"
            }
        ]
    },
    {
        "name": "slot_hours",
        "type": "FLOAT",
        "mode": "NULLABLE"
    },
    {
        "name": "process_timestamp",
        "type": "TIMESTAMP",
        "mode": "NULLABLE"
    }
]
EOF
```

2023-06-20 19:27 UTC, ppaglilla approved these changes

2023-06-20 19:34 UTC, merged